djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('schedule/', include("schedule.urls")),
    path('', include("login.urls")),
    path('register/', include("register.urls")),
    path('user/', include("user.urls")),
]

login/urls.py
from django.urls import path
from . import views
app_name = "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name ="login"),
    path('index/', views.index, name='index'),
]
#moi app cu tao duong dan cua rieng no, vi da khai bao o main nen no ok het

user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('/request', views.requ, name ="request"),
    path('/setup', views.setup, name ="setup"),
    path('/setting', views.sett, name ="setting"),
    path('/changeinfo2', views.changeinfouser2, name = "changeinfouser2"),
    path('/changeinfo1', views.changeinfouser1, name = "changeinfouser1"),
    path('/accept', views.accept, name = "accept"),
    path('/navi', views.navi, name="navi"),
]

login/models.py
import time

from django.db import models
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
import psycopg2
from psycopg2 import Error
from djangoProject1.common import *

# Create your models here.
# string, int, ...
class BOAUser(): #tao class
    def __init__(self, id, username, password, email, usertype): #ham __init__ la ham khoi tao
        self.id = id
        self.username = username
        self.password = password
        self.email = email
        self.type = usertype
        self.typefix = tranferUsertype(int(self.type))
#dung de lay thong tin tu database, bang boauser
BOAUsers = list() #tao doi tuong, list

#front end: username, password
#back end: lay het dataser, so sanh dua ket qua
# database: table
# back end: class
def MigrateDataBOAUser(): #lay data trong database
    data = HookData("DATABASE")
    BOAUsers.clear()
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        #bat ki ham nao tuong tac database deu phai co buoc connection va cursor, chi khac nhau phia duoi
        # Executing a SQL query
        cursor.execute("select * from boauser")
        #execute khac nhau tuy muc dich, quan trong nhat
        # Fetch result
        records = cursor.fetchall() #luu du lieu cua viec thuc hien cau lenh
        # The function code
        for row in records:
            temp = BOAUser(row[0], row[1], row[2], row[3], row[4])
            BOAUsers.append(temp)
        return 1
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            connection.close()

login/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from login.models import *
import time
# Create your views here.
def index(request):
    return render(request, 'login/login.html') #trang login chua nhap gi vao
def login(request):
    if request.method == "POST":
        submit = str(request.POST['submit'])
        username = str(request.POST['username'])
        password = str(request.POST['password'])
        MigrateDataBOAUser() #lay data tu database
        #database
        #username, password
        if submit == "Login":
            for x in BOAUsers:
                if x.username == username and x.password == password:
                    if x.typefix == "ROOT":
                        context = {'user': x, 'id': x.id, 'role': x.typefix, 'request_mode': 1, 'setup_mode': 1, 'edit_mod': 1}
                        return render(request, 'user/settings.html', context)
                    elif x.typefix == "ADMIN":
                        context = {'user': x, 'id': x.id, 'role': x.typefix, 'setup_mode': 1, 'edit_mode': 1}
                        return render(request, 'user/settings.html', context)
                    elif x.typefix == "ASSISTANT":
                        context = {'user': x, 'id': x.id, 'role': x.typefix, 'edit_mode': 1}
                        return render(request, 'user/settings.html', context)
                    elif x.typefix == "USER":
                        context = {'user': x, 'id': x.id, 'role': x.typefix}
                        return render(request, 'user/settings.html', context)
            context = {'login': 1}
            return render(request, 'login/result.html', context)

login/templates/login/login.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Login</title>
	<meta name="description" content="Main Login Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script type="text/javascript" src="{% static 'main.js' %}"></script>
	<meta name="theme-color" content="#fafafa">
</head>

<header>
	<nav id="nav_login">
		<a href="{% url 'login:index' %}" class="left current">Login</a>
	</nav>
</header>
<body>
    <main>
    <h1> Login page to BOA! </h1>
    <div class="user-pass">
			<form action="{% url 'login:login' %}" method="post">
				{% csrf_token %}
				<label for="username">Username:</label>
				<input type="text" name="username"><br>
				<label for="password">Password:</label>
				<input name="password" type="password">
				<ul>
					<input type="submit" name="submit" value="Login">

				</ul>
    		</form>
	</div>
    </main>
</body>
</html>

login/templates/login/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<body>
    {% if login %}
    <h1> Your username or password incorrect. </h1>
    {% endif %}
    {% if no_account%}
    <h1> Your email incorrect. </h1>
    {% endif %}
     {% if has_account%}
    <h1> The code has sent in your email. Check it!</h1>
      <form action="{% url 'login:forgot_code' %}" method="post">
				{% csrf_token %}
				<label for="code">Please input your code:</label>
				<input type="text" name="code"><br>
                <input type="submit" name="submit" value="Verify">
      </form>
    {% endif %}
    <a href =" {% url 'login:index' %}">
        Click to return login page!
    </a>

</body>
</html>