djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('schedule/', include("schedule.urls")),
    path('', include("login.urls")),
    path('register/', include("register.urls")),
    path('user/', include("user.urls")),
]

register/urls.py
from django.urls import path
from . import views
app_name = "register"
urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.save, name='save'),
]

user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('/request', views.requ, name ="request"),
    path('/setup', views.setup, name ="setup"),
    path('/setting', views.sett, name ="setting"),
    path('/changeinfo2', views.changeinfouser2, name = "changeinfouser2"),
    path('/changeinfo1', views.changeinfouser1, name = "changeinfouser1"),
    path('/accept', views.accept, name = "accept"),
    path('/navi', views.navi, name="navi"),
]

register/models.py
import random

from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
import psycopg2
from psycopg2 import Error
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from djangoProject1.common import *
from django.db import models
from login.models import BOAUsers, MigrateDataBOAUser
import random
# Create your models here.
class RegistrationRequest():
    def __init__(self, eid, proposedUserName, proposedPassword, submittedEmailAddress, requestedUserType):
        self.id = eid
        self.proposedUserName = proposedUserName
        self.proposedPassword = proposedPassword
        self.submittedEmailAddress = submittedEmailAddress
        self.requestedUserType = requestedUserType
RegistrationRequests = list()

def MigrateDataRegis(): #=MigrateDataBOA
    data = HookData("DATABASE")
    RegistrationRequests.clear()
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        # Executing a SQL query
        cursor.execute("select * from registrationrequest")
        # Fetch result
        records = cursor.fetchall()
        # The function code
        for row in records:
            temp = RegistrationRequest(row[0], row[1], row[2], row[3], row[4])
            RegistrationRequests.append(temp)
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            connection.close()
def SendCredentialMail(email, username, password):   #email nguoi nhan, username and password duoc tao ra
    data = HookData("SENDMAIL") #
    fromadd = data["from"]  #dia chi email nguoi gui
    toadd = email       #email nguoi nhan
    msg = MIMEMultipart()    #quy tac, tao ra doi tuong msg
    msg['From'] = fromadd
    msg['To'] = toadd
    msg['Subject'] = "Credential"
    header = "This is an email automatically sent from BOA Auto Send. Please do not reply to this message!" + "\n"
    footer = "Use the credential to login in BOA"
    body = header + "Username: " + username + "\n" + "Password: " + password + "\n" + footer
    #dong goi msg
    msg.attach(MIMEText(body, 'plain'))

    #server smtp
    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.ehlo()
    #dang nhap
    server.login(fromadd, data["password"])   #login
    text = msg.as_string()
    server.sendmail(fromadd, toadd, text) #send
    server.quit()

    return True
def checkRegisterEmail(request):
    # Rea file
    data = HookData("DATABASE")
    try:
    # Connect to an existing database
        connection = psycopg2.connect(**data)
    # Create a cursor to perform database operations
        cursor1 = connection.cursor()
        cursor2 = connection.cursor()
    # Executing a SQL query

        cursor2.execute("SELECT submited_emailadress from registrationrequest;")
    # Fetch result

        record2 = cursor2.fetchall()
    # The function code

        for row in record2:
            if (request == row[0]):
                return True
        #Buoc 3
        return False   #=khong ton tai
    except (Exception, Error) as error:
        return True
    finally:
        if (connection):
            cursor1.close()
            cursor2.close()
            connection.close()
def CreateRegistrationUser(email, usertype):
    if checkRegisterEmail(email) == True:   #co ton tai
        return False
    #cau hinh lai du lieu
    type = int(usertype)
    MigrateDataBOAUser()
    for i in BOAUsers:
        if i.email == email:
            temp = i
    username = temp.username
    password = temp.password
    data = HookData("DATABASE")
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        records = (temp.id, username, password, email, type)
        query = """insert into registrationrequest(user_id, proposed_username, proposed_password, submited_emailadress, request_user_type) 
                       values (%s,%s,%s,%s,%s)"""
        cursor.execute(query, records)
        connection.commit()
        return True
    except (Exception, Error) as error:
        return False
    finally:
        if (connection):
            cursor.close()
            connection.close()
def DropRequest(email):
    data = HookData("DATABASE")
    drop_data = (email,)
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        # Executing a SQL query
        query = "delete from registrationrequest where submited_emailadress = %s"
        cursor.execute(query, drop_data)
        connection.commit()
        return True
    except (Exception, Error) as error:
        return False
    finally:
        if (connection):
            cursor.close()
            connection.close()
def createBOAUser(eid, username, password, email, type):
    data = HookData("DATABASE")
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        print(connection)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        # Executing a SQL query
        records = ()
        records += (eid, username, password, email, type)
        query = """insert into boauser(eid, user_name, pass_word, email_address, user_type) 
                       values (%s,%s,%s,%s,%s)"""
        cursor.execute(query, records)
        connection.commit()
        return 1
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            connection.close()
def UpdateBOAUser(type, eid):
    data = HookData("DATABASE")
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        print(connection)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        # Executing a SQL query
        records = (type, eid)
        query = """update boauser set user_type=%s where eid=%s"""
        cursor.execute(query, records)
        connection.commit()
        return 1
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            connection.close()
def DeleteBOAUser(eid):
    data = HookData("DATABASE")
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        print(connection)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        # Executing a SQL query
        records = (eid,)
        query = """delete from boauser where eid=%s"""
        cursor.execute(query, records)
        connection.commit()
        return 1
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            connection.close()

register/forms.py
from django.forms import ModelForm
from django import forms
from register.models import *
from register.views import *
class RegistrationForm(forms.Form):
    email = forms.EmailField()
    usertype = forms.CharField()

register/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
import psycopg2
from psycopg2 import Error
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from register.models import *
from djangoProject1.common import *

from schedule.models import MigrateData, Employees
from login.models import MigrateDataBOAUser, BOAUsers
def index(request):
    id = str(request.POST['id'])
    MigrateDataBOAUser()
    for i in BOAUsers:
        if id == str(i.id):
            boa = i
    context = {'id': id, 'boa': boa}
    return render(request, 'register/base.html', context)
def save(request):
            #lay data
            id = str(request.POST['id'])
            email = str(request.POST['email'])
            user_data_type = request.POST['usertype']
            #thuc hien 1 function
            status = CreateRegistrationUser(email, user_data_type)
            context = {'status': status, 'id': id}
            return render(request, 'register/result.html', context)

register/templates/register/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right current">
              <input type="hidden" name="id" value={{ id }} >
        </form>
	</nav>
</header>
<body>
    <main>
    <h1> Registration Request Form </h1>
        <div class="register">
    <form action = "{% url 'register:save' %}" method ="post">
        {%csrf_token%}
	  <div>
          <h2> EID: {{ id }}</h2>
		  <h2> Name: {{ boa.username }}</h2>
          <h2> Email: {{ boa.email }}</h2>
	  </div>
	  <h2>User Type</h2>
	  <ul class="usertype">
		  <li>
			  <input type="radio" id="ROOT" name="usertype" value="3">
			  <label for="ROOT">ROOT</label>
		  </li>
		  <li>
			  <input type="radio" id="ADMIN" name="usertype" value="2">
			  <label for="ADMIN">ADMIN</label>
		  </li>
		  <li>
			  <input type="radio" id="assist" name="usertype" checked="checked" value="1">
			  <label for="assist">ASSISTANT</label>
		  </li>
	  </ul>
        <input type="hidden" name="id" value={{ id }}>
        <input type="hidden" name="email" value={{ boa.email }}>
        <input type="submit" value="Submit">
    </form>
            </div>
        </main>
</body>
</html>

register/templates/register/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right current">
              <input type="hidden" name="id" value={{ id }} >
        </form>
	</nav>
</header>
<body>
    {% if status  == 1 %}
    <h1> Your request has been received. Please wait the Root User accept. </h1>
    {% elif status  == 0 %}
    <h1> Registration failed because the email you used already exists. </h1>
    {% endif %}
</body>
</html>