djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('schedule/', include("schedule.urls")),
    path('', include("login.urls")),
    path('register/', include("register.urls")),
    path('user/', include("user.urls")),
]

login/urls.py
from django.urls import path
from . import views
app_name = "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name ="login"),
    path('index/', views.index, name='index'),
]
#moi app cu tao duong dan cua rieng no, vi da khai bao o main nen no ok het

register/urls.py
from django.urls import path
from . import views
app_name = "register"
urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.save, name='save'),
]

schedule/urls.py
from django.urls import path
from . import views
from django.urls import path
from . import views
app_name = "schedule"
urlpatterns = [
    path('', views.index, name='index'),
    path('generate/', views.generate, name='generate'),
    path('editempl/', views.editempl, name='editempl'),
    path('editcreateemploy/', views.edit_create_employ, name='edit_create'),
    path('editassi/', views.editassi, name='editassi'),
    path('editcreateassi/', views.edit_create_assi, name='edit_create_assi'),
    path('editshift/', views.editshift, name='editshift'),
    path('editcreateshift/', views.edit_create_shift, name='edit_create_shift'),
    path('editunav/', views.editunav, name='editunav'),
    path('editcreateunav/', views.edit_create_unav, name='edit_create_unav'),
    path('manual/',views.manual, name='manual'),

]

user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('/request', views.requ, name ="request"),
    path('/setup', views.setup, name ="setup"),
    path('/setting', views.sett, name ="setting"),
    path('/changeinfo2', views.changeinfouser2, name = "changeinfouser2"),
    path('/changeinfo1', views.changeinfouser1, name = "changeinfouser1"),
    path('/accept', views.accept, name = "accept"),
    path('/navi', views.navi, name="navi"),
]

user/models.py
from django.db import models

# Create your models here.
import psycopg2
from register.models import *
from schedule.models import *
from login.models import *
def UpdateUser(id, newmail, newpassword):
    data = HookData("DATABASE")
    print(data)
    id_fix = int(id)
    try:
        # Connect to an existing database
        connection = psycopg2.connect(**data)
        print(connection)
        # Create a cursor to perform database operations
        cursor = connection.cursor()
        cursor2 = connection.cursor()
        # Executing a SQL query
        if newmail!='':
            fix = ()
            fix +=(newmail, id_fix, )
            query = """update boauser set email_address=%s where eid=%s"""
            cursor.execute(query, fix)
            connection.commit()
        if newpassword!='':
            fix2 = ()
            fix2 += (newpassword, id_fix, )
            query2 = """update boauser set pass_word=%s where eid=%s"""
            cursor2.execute(query2, fix2)
            connection.commit()
        return 1
    except (Exception, Error) as error:
        return 0
    finally:
        if (connection):
            cursor.close()
            cursor2.close()
            connection.close()
    return 0

user/views.py
from django.shortcuts import render

# Create your views here.
from register.models import *
from user.models import *
from django.http import HttpResponse
# Create your views here.
def setup(request):
    s = str(request.POST['id'])
    MigrateDataBOAUser()
    for x in BOAUsers:
        if str(x.id) == s:
            if x.typefix == "ROOT":
                context = {'user': x, 'id': x.id, 'role': x.typefix, 'request_mode': 1, 'setup_mode': 1, 'edit_mod': 1}
            elif x.typefix == "ADMIN":
                context = {'user': x, 'id': x.id, 'role': x.typefix, 'setup_mode': 1, 'edit_mode': 1}
            elif x.typefix == "ASSISTANT":
                context = {'user': x, 'id': x.id, 'role': x.typefix, 'edit_mode': 1}
            elif x.typefix == "EMPLOYEE":
                context = {'user': x, 'id': x.id, 'role': x.typefix}
    return render(request, 'user/setup.html', context)
def navi(request):
    s = str(request.POST['id'])
    c = str(request.POST['check'])
    if c=="Setup Employee":
        MigrateData()
        context = {'id':s, 'data':Employees}
        return render(request, 'schedule/employee.html', context)
    if c=="Setup Assignment":
        MigrateData()
        context = {'id':s, 'data':Assignments}
        return render(request, 'schedule/assignment.html', context)
    if c=="Setup Shift":
        li, data = shift_config()
        context = {'id':s, 'list':li, 'data':data}
        return render(request, 'schedule/shift.html', context)
def requ(request):
        s = str(request.POST['id'])
        MigrateDataRegis()
        context = {'id': s, 'data': RegistrationRequests}
        return render(request, 'user/requests.html', context)
def sett(request):
        id = str(request.POST['id'])
        MigrateDataBOAUser()
        for x in BOAUsers:
            if str(x.id) == id:
                if x.typefix == "ROOT":
                    context = {'user': x, 'id': x.id, 'role': x.typefix, 'request_mode': 1, 'setup_mode': 1, 'edit_mod': 1}
                    return render(request, 'user/settings.html', context)
                elif x.typefix == "ADMIN":
                    context = {'user': x, 'id': x.id, 'role': x.typefix, 'setup_mode': 1, 'edit_mode': 1}
                    return render(request, 'user/settings.html', context)
                elif x.typefix == "ASSISTANT":
                    context = {'user': x, 'id': x.id, 'role': x.typefix, 'edit_mode': 1}
                    return render(request, 'user/settings.html', context)
                elif x.typefix == "USER":
                    context = {'user': x, 'id': x.id, 'role': x.typefix}
                    return render(request, 'user/settings.html', context)
def changeinfouser1(request):
    id = str(request.POST['id'])
    context = {'id':id}
    return render(request, 'user/changeinfouser.html', context)
def changeinfouser2(request):
        id = str(request.POST['id'])
        new_mail = str(request.POST['email_ros'])
        new_password = str(request.POST['password'])
        old_password = str(request.POST['password_1'])
        MigrateDataBOAUser()
        for x in BOAUsers:
            if str(x.id) == id:
                idk = id
                if str(x.password) == old_password:
                    s = UpdateUser(id, new_mail, new_password)
                    context = {'status': s, 'id': idk}
                else:
                    s = 0
                    context ={'status': s, 'id': idk}
        return render(request, 'user/changeinfouser_res.html', context)
def accept(request):
        id = str(request.POST['id'])
        context = {'id': id}
        check = str(request.POST['check'])
        submit = str(request.POST['submit'])
        MigrateDataRegis()
        for x in RegistrationRequests:
            MigrateDataBOAUser()
            if str(x.id) == str(check):
                if submit=="Accept":
                    UpdateBOAUser(x.requestedUserType, x.id)
                    DropRequest(x.submittedEmailAddress)
                    context = {'id':id, 'ac':1}
                else:
                    DropRequest(x.submittedEmailAddress)
                    context = {'id':id}
        return render(request, 'user/request_res.html', context)

user/templates/user/changeinfouser.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Login</title>
	<meta name="description" content="Main Login Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script type="text/javascript" src="{% static 'main.js' %}"></script>
	<meta name="theme-color" content="#fafafa">
</head>

<header>
	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right current">
              <input type="hidden" name="id" value={{ id }} >
        </form>
	</nav>
</header>
<body>
    <main>
    <h1> This page support you change user information! </h1>
    <div class="user-pass">
			<form action="{% url 'user:changeinfouser2' %}" method="post">
				{% csrf_token %}
                <input type="hidden" name="id" value={{ id }}>
				<label for="email_ros">New email here (blank is not change):</label>
				<input type="text" name="email_ros"><br>
				<label for="password">New password here (blank is not change):</label>
				<input name="password" type="password">
                <label for="password_1">Old password:</label>
				<input name="password_1" type="password">
				<ul>
					<input type="submit" value="Submit">
				</ul>
    		</form>
	</div>
    </main>
</body>
</html>

user/templates/user/changeinfouser_res.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<body>
    {% if status  == 1 %}
    <h1> Data fix success. </h1>
    {% elif status  == 0 %}
    <h1> Fail </h1>
    {% endif %}
    <form action="{% url 'user:setting' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value={{ id }} >
                    <input type="submit" id="save" value="Back">
    </form>

</body>
</html>

user/templates/user/request_res.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<body>
    {% if ac %}
    <h1> Accept success. </h1>
        {% else %}
    <h1> Refuse success. </h1>
    {% endif %}
    <form action="{% url 'user:request' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value={{ id }} >
                    <input type="submit" id="save" value="Back">
    </form>

</body>
</html>

user/templates/user/requests.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Requests</title>
	<meta name="description" content="Active Requests Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>

	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right current">
              <input type="hidden" name="id" value={{ id }} >
        </form>

	</nav>
</header>
<body>
	<main>
        <div class="large">
			<h1>Request Queue</h1>
            <form name="" action="{% url 'user:accept' %}" method="post">
            {% csrf_token %}
			<table>
				<tbody>
					<tr class="header">
						<th style="width:5%">Request No.</th>
						<th style="width:20%">Prop. Username</th>
						<th style="width:20%">Prop. Password</th>
						<th>Email Address</th>
						<th style="width:20%">Requested Type</th>
					</tr>
					<!-- Use this as template to import Requests -->

                    {% for i in data %}
                    <tr>
						<td><input type="radio"  name="check" checked="checked" value={{ i.id }}></td>
						<td>{{ i.proposedUserName }}</td>
						<td class="ppass">{{ i.proposedPassword }}</td>
						<td>{{ i.submittedEmailAddress }}</td>
						<td>{{ i.requestedUserType }}</td>
					</tr>
                    {% endfor %}
				</tbody>
			</table>
            <ul>
                <input type="hidden" name="id" value= {{ id }}>
				<input type="submit" name="submit" value="Accept" >
                <input type="submit" name="submit" value="Refuse" >
            </ul>
             </form>
        </div>
	</main>
</body>

</html>

user/templates/user/settings.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Settings</title>
	<meta name="description" content="Settings Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>

	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Dashboard" class="right current">
              <input type="hidden" name="id" value={{ id }} >

        </form>
        {% if setup_mode %}
        <form id="empl" method="post" action="{% url 'user:setup' %}" class="left">
                {% csrf_token %}
              <input type="submit" name="empl" value="Set up" class="left">
              <input type="hidden" name="id" value={{ id }} >
        </form>
        {% endif %}
        <form id="edit" method="post" action="{% url 'schedule:index' %}">
            {% csrf_token %}
              <input type="submit" name="edit" value="Schedule" class="">
              <input type="hidden" name="id" value={{ id }} >
        </form>
        {% if request_mode %}
        <form id="requ" method="post" action="{% url 'user:request' %}">
            {% csrf_token %}
              <input type="submit" name="request" value="Request" class="">
              <input type="hidden" name="id" value={{ id }} >
        </form>
        {% endif %}
	</nav>
</header>
<body>
	<main>
		<div class="large">
			<div class="settings">
				<div class="editemployrow">
                    <h2>Username:  </h2>
                    <h3>{{ user.username }}</h3>

				</div>
				<div class="editemployrow">
                    <h2>ID:</h2>
                    <h3>{{ user.id }}</h3>

				</div>
				<div class="editemployrow">
					<h2>User Type:   </h2>
                    <h3>{{ user.typefix }}</h3>

				</div>
				<div class="editemployrow">
					<h2>Password:</h2>
					<h3>********</h3>
				</div>
				<div class="editemployrow">
					<h2>Email Address:</h2>
					<h3>{{ user.email }}</h3>
				</div>
                <form action="{% url 'user:changeinfouser1' %}" method="post">
                    {% csrf_token %}

                        <input type="hidden" name="id" value= {{ id }}>

                        <input type="submit" name="save" value="Change your info">

                </form>
                <form action="{% url 'login:index' %}" method="get">
                    {% csrf_token %}

                        <input type="submit" id="save" value="Log out">


                </form>
                <form action="{% url 'register:index' %}" method="post">
                    {% csrf_token %}
                        <input type="hidden" name="id" value="{{ id }}">

                        <input type="submit"  value="Upgrade your account">
                </form>
            </div>
		</div>
	</main>
</body>

</html>

user/templates/user/setup.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Requests</title>
	<meta name="description" content="Active Requests Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>

	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right current">
              <input type="hidden" name="id" value={{ id }} >
        </form>

	</nav>
</header>
<body>
	<main>
            <form id="setup" method="post" action="{% url 'user:navi' %}">
                {% csrf_token %}
            <ul>
                <input type="hidden" name="id" value= {{ id }}>
				<input type="submit"  name="check" value="Setup Employee" >
                <br>
                <input type="submit"  name="check" value="Setup Assignment" >
                <br>
                <input type="submit"  name="check" value="Setup Shift" >
            </ul>
             </form>
	</main>
</body>

</html>