djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('schedule/', include("schedule.urls")),
    path('', include("login.urls")),
    path('register/', include("register.urls")),
    path('user/', include("user.urls")),
]

login/urls.py
from django.urls import path
from . import views
app_name = "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name ="login"),
    path('index/', views.index, name='index'),
]
#moi app cu tao duong dan cua rieng no, vi da khai bao o main nen no ok het

schedule/urls.py
from django.urls import path
from . import views
from django.urls import path
from . import views
app_name = "schedule"
urlpatterns = [
    path('', views.index, name='index'),
    path('generate/', views.generate, name='generate'),
    path('editempl/', views.editempl, name='editempl'),
    path('editcreateemploy/', views.edit_create_employ, name='edit_create'),
    path('editassi/', views.editassi, name='editassi'),
    path('editcreateassi/', views.edit_create_assi, name='edit_create_assi'),
    path('editshift/', views.editshift, name='editshift'),
    path('editcreateshift/', views.edit_create_shift, name='edit_create_shift'),
    path('editunav/', views.editunav, name='editunav'),
    path('editcreateunav/', views.edit_create_unav, name='edit_create_unav'),
    path('manual/',views.manual, name='manual'),

]

user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('/request', views.requ, name ="request"),
    path('/setup', views.setup, name ="setup"),
    path('/setting', views.sett, name ="setting"),
    path('/changeinfo2', views.changeinfouser2, name = "changeinfouser2"),
    path('/changeinfo1', views.changeinfouser1, name = "changeinfouser1"),
    path('/accept', views.accept, name = "accept"),
    path('/navi', views.navi, name="navi"),
]

schedule/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from schedule.models import *
from register.models import *
from login.models import *
def index(request):
    id = str(request.POST['id'])
    s = list(MigrateSchedule())
    MigrateData()

    for i in s: # sau khi edit nhân vien, nêu chọn xoá nhan vien -> nhan vien bi xoá trong thoi khoá biểu
        find = 0
        for j in Employees:
            if i[0]==j.eid:
                find = 1
        if find==0:
            s.remove(i)

    for i in s: # biến đổi lần lượt id = name cua emp.
        for j in Employees:
            if i[0]==j.eid:
                i[0] = j.name
    for i in range(len(Employees)-len(s)): # edit employee --> thêm nhân viên
        matrix = []
        matrix.append(Employees[len(Employees)+i-1].name)
        for i in range(1,15):
            matrix.append(-1)
        matrix.append(0)
        s.append(matrix)
    context = []
    for i in range(len(Employees)): #upload from employee table to schedule
        temp = []
        context.append(temp)
    for i in range(len(s)): # s la du lieu schedule back-end hieu, context la du lieu schedule hien thi tren web.
        # câu lệnh nay de chuyen s thanh context
        context[i].append(s[i][0]) #them gia trị name cua s vao context
        for j in range(1, 15):
            context[i].append(change(s[i][j]))  #biên đổi thứ tuự chữ số vào asignment tuong ứng
        context[i].append(s[i][15]) # thêm giá trị cost hours



    num, lis= Assignment_fill()  #num=4, lis ["expo", "line", "prep",""] ,expo Am, expo pm--> expo
    list_name_assignment = list(lis)
    super_context = []
    number_week = show_assignment() # số nhân viên làm 1 ca trong tuần
    for i in range(num):
        temp = []
        temp.append(list_name_assignment[i]) # add asignment cua num vào cột đâu tiên cua schedule
        for j in range(len(Shifts)):
            temp.append(number_week[i][j]) # thêm vào số nhân viên cần làm trong tuần theo hang ngang
        super_context.append(temp)
        con = {'schedule': context, 'number_week': super_context, 'id': id} #dictionary
    MigrateDataBOAUser()
    for i in BOAUsers:
        if str(i.id) == id:
            temp = i
    if int(temp.type) > 0: # mode >=1,  phan quyen type > 0, de co quyên edit
        con = {'schedule': context, 'number_week': super_context, 'id': id, 'mode':1}
    return render(request, 'schedule/schedule.html', con)
# Create your views here.


def generate(request):
    id = str(request.POST['id'])
    context = {'id':id}
    submit = str(request.POST['submit'])
    if submit=="Generate Schedule":
        while 1: # tìm cho đến khi tìm dc schedule
            s = create_schedule() #chay thuát toán trong model tim f schedule
            if s == 1:
                return render(request, 'schedule/res.html', context)
    else: #manual edit
        MigrateData()
        num, l = Assignment_fill()
        assi = ["No work"] + list(l) # ("ẽpo",,,"no work")
        context ={'id':id, 'emp':Employees, 'assi':assi}
        return render(request, 'schedule/manual.html', context)

def editempl(request):
        id = str(request.POST['id'])
        submit = str(request.POST['submit'])
        if submit == "Edit Employee":
            check = str(request.POST['check'])
            MigrateData()
            for i in Employees:
                if str(i.eid) == check:
                    context = {'data': i, 'id': id}
                    return render(request, 'schedule/editemploy.html', context)
        elif submit == "Create Employee":
            context = {'id': id}
            return render(request, 'schedule/addemploy.html', context)
        elif submit == "Delete Employee":
            check = str(request.POST['check'])
            dataset = (check,)
            DeleteValue("e", dataset)
            MigrateData()
            context = {'id': id, 'data': Employees}
            return render(request, 'schedule/employee.html', context)
def edit_create_employ(request):
    id = str(request.POST['id'])
    submit = str(request.POST['submit'])
    eid = str(request.POST['eid'])
    name = str(request.POST['name'])
    title = int(request.POST['title'])
    minhour = int(request.POST['minhour'])
    maxhour = int(request.POST['maxhour'])

    if submit == "Accept Create":
        email = str(request.POST['e_mail'])
        dataset = (eid, name, title, minhour, maxhour)
        status = AddValue("e", dataset)
        if status==1:
            username, password = Create_Credential(email)
            SendCredentialMail(email,username,password)
            createBOAUser(eid, username, password, email, "0")
            context = {'create_empl_done':1, 'id':id}
        else:
            context = {'fail': 1, 'id': id}
        return render(request, 'schedule/edit_create_res.html', context)
    elif submit == "Accept Edit":
        old_eid = int(request.POST['old'])
        dataset = (eid, name, title, minhour, maxhour, old_eid)
        status = EditValue("e", dataset)
        if status == 1:
            context = {'edit_empl_done': 1, 'id': id}
        else:
            context = {'fail': 1, 'id': id}
        return render(request, 'schedule/edit_create_res.html', context)
    elif submit == "Navigate Unavailable Time":
        MigrateData()
        context = {'id': id, 'name': name, 'eid': eid}
        for i in Employees:
            if str(i.eid) == eid:
                context = {'id':id, 'data': i.UnavailableTime, 'name':name, 'eid':eid}
                return render(request, 'schedule/unavailabletime.html', context)
        return render(request, 'schedule/unavailabletime.html', context)


def editassi(request):
    id = str(request.POST['id'])
    submit = str(request.POST['submit'])
    if submit == "Edit Assignment":
        check = str(request.POST['check'])
        s = check.split("/")
        MigrateData()
        for i in Assignments:
            if str(i.taskName) == s[0] and i.tag == s[1]:
                context = {'data': i, 'id': id}
                return render(request, 'schedule/editassign.html', context)
    elif submit == "Create Assignment":
        context = {'id': id}
        return render(request, 'schedule/addassign.html', context)
    elif submit == "Delete Assignment":
        check = str(request.POST['check'])
        check_fix = check.split("/")
        dataset = (check_fix[0], check_fix[1])
        DeleteValue("a", dataset)
        UpdateShiftDel(check_fix[0])
        MigrateData()
        context = {'id': id, 'data': Assignments}
        return render(request, 'schedule/assignment.html', context)
def edit_create_assi(request):
    id = str(request.POST['id'])
    submit = str(request.POST['submit'])
    taskname = str(request.POST['taskname'])
    start = str(request.POST['start'])
    end = str(request.POST['end'])
    min_title = int(request.POST['title'])
    tag = str(request.POST['tag'])
    if submit == "Accept Create":
        dataset = (taskname, start, end, min_title, tag)
        status = AddValue("a", dataset)
        if status==1:
            context = {'create_assi_done':1, 'id':id}
            UpdateShift()
        else:
            context = {'fail': 1, 'id': id}
        return render(request, 'schedule/edit_create_res.html', context)
    elif submit == "Accept Edit":
        old = str(request.POST['old'])
        old_s = old.split("/")
        dataset = (taskname, start, end, min_title, tag, old_s[0], old_s[1])
        status = EditValue("a", dataset)
        if status == 1:
            context = {'edit_assi_done': 1, 'id': id}
        else:
            context = {'fail': 1, 'id': id}
        return render(request, 'schedule/edit_create_res.html', context)
class temp_l:
    def __init__(self, l, n ):
        self.l = l
        self.n = n
def editshift(request):
    id = str(request.POST['id'])
    submit = str(request.POST['submit'])
    if submit == "Edit Shift":
        check = str(request.POST['check'])
        s = check.split("/")
        MigrateData()
        for i in Shifts:
            if str(i.day) == s[0] and i.tag == s[1]:
                num, li = Assignment_fill()
                l = list(dict.fromkeys(li))
                num_l = [0]*num
                for j in i.shift_assignment:
                    for k in range(num):
                        if j.assignment.taskName == l[k]:
                            num_l[k] = j.number
                li =[]
                for k in range(num):
                    li.append(temp_l(l[k], num_l[k]))
                context = { 'id': id, 'list':li, 'day':s[0], 'tag':s[1]}
                return render(request, 'schedule/editshift.html', context)
    elif submit == "Delete Shift":
        check = str(request.POST['check'])
        check_fix = check.split("/")
        li, data = shift_config()
        st =""
        for i in range(len(li)):
                st = st + li[i] + "=" + "0" +","
        dataset=(st,)
        dataset+=(check_fix[0], check_fix[1])
        EditValue("s", dataset)
        li, data = shift_config()
        context = {'id': id, 'data': data, 'list':li}
        return render(request, 'schedule/shift.html', context)
def edit_create_shift(request):
    id = str(request.POST['id'])
    n, li = Assignment_fill()
    l = list(dict.fromkeys(li))
    num = [0] * n
    for i in range(n):
        num[i] = int(request.POST[l[i]])

    old = str(request.POST['old'])
    old_s = old.split("/")
    st = ""
    for i in range(n):
        st = st + l[i] + "=" + str(num[i]) + ","
    dataset = (st, old_s[0], old_s[1])
    status = EditValue("s", dataset)
    if status == 1:
        context = {'edit_shift_done': 1, 'id': id}
    else:
        context = {'fail': 1, 'id': id}
    return render(request, 'schedule/edit_create_res.html', context)

def editunav(request):
    id = str(request.POST['id'])
    eid = str(request.POST['eid'])
    name = str(request.POST['name'])

schedule/templates/schedule/addemploy.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Employee Editor</title>
	<meta name="description" content="Edit Employee Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->


	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="back" method="post" action="{% url 'user:setup' %}">
                {% csrf_token %}
              <input type="submit" name="empl" value="Back">
              <input type="hidden" name="id" value={{ id }} >

        </form>
	</nav>
</header>
<body>
	<main>
        <form method="post" action="{% url 'schedule:edit_create' %}">
            {% csrf_token %}
		<div class="large">

			<div class="editemploy">
				<div class="editemployrow">
					<h2>Employee ID:</h2>
					<input type="text"  name="eid">
				</div>
				<div class="editemployrow">
					<h2>Name:</h2>
					<input type="text"  name="name">
				</div>
				<div class="editemployrow">
					<h2>Brigade Title:</h2>
					<select name="title" id="brtitle">
						<option value="4">Kitchen Leader</option>
						<option value="3">Sous Chef</option>
						<option value="2">Line Cook</option>
						<option value="1">Junior Cook</option>
						<option value="0">Dishwasher</option>
					</select>
				</div>
				<div class="editemployrow">
					<h2>Min Hours:</h2>
					<input type="number"  name="minhour" min="0" max="84" step="1">
				</div>
				<div class="editemployrow">
					<h2>Max Hours:</h2>
					<input type="number"  name="maxhour" min="0" max="84" step="1">
				</div>
                <div class="editemployrow">
					<h2>Email:</h2>
					<input type="text"  name="e_mail" >
				</div>
			</div>
			<ul>
                <input type="hidden" name="id" value="{{ id }}">
                <input type="submit" value="Accept Create" name="submit">
			</ul>
		</div>
        </form>
	</main>
</body>

</html>

schedule/templates/schedule/addunvai.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Employee Unavailabla Time Editor</title>
	<meta name="description" content="Edit Employee Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->


	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="back" method="post" action="{% url 'user:setup' %}">
                {% csrf_token %}
              <input type="submit" name="empl" value="Back">
              <input type="hidden" name="id" value={{ id }} >

        </form>
	</nav>
</header>
<body>
	<main>
        <form method="post" action="{% url 'schedule:edit_create_unav' %}">
            {% csrf_token %}
		<div class="large">

			<div class="editemploy">
				<div class="editemployrow">
					<h2>Employee ID: {{ eid }}</h2>

				</div>
				<div class="editemployrow">
					<h2>Name: {{ name }}</h2>

				</div>
                <div class="editemployrow">
					<h2>Day: </h2>
					<select name="day" id="brtitle">
						<option value="Mon">Monday</option>
						<option value="Tue">Tuesday</option>
						<option value="Wed">Wednesday</option>
						<option value="Thu">Thursday</option>
						<option value="Fri">Friday</option>
                        <option value="Sat">Saturday</option>
                        <option value="Sun">Sunday</option>
					</select>
				</div>
                <div class="editemployrow">
					<h2>Reason:</h2>
					<input type="text"  name="reason" >
				</div>
				<div class="editemployrow">
					<h2>Time start (military time):</h2>
					<input type="text"  name="start" >
				</div>
				<div class="editemployrow">
					<h2>Max Hours (military time):</h2>
					<input type="text"  name="end" >
				</div>

			</div>
			<ul>
                <input type="hidden" name="id" value="{{ id }}">
                 <input type="hidden" name="eid" value="{{ eid }}">
                <input type="submit" value="Accept Create" name="submit">
			</ul>
		</div>
        </form>
	</main>
</body>

</html>

schedule/templates/schedule/assignment.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Assignments</title>
	<meta name="description" content="Current Employees Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>

	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setup' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right">
              <input type="hidden" name="id" value={{ id }} >
        </form>
	</nav>
</header>
<body>
	<main>
		<div class="large">
            <form action="{% url 'schedule:editassi' %}" method="post">
            {% csrf_token %}
			<table>
				<tbody class="emp-list">
					<tr class="header">
						<th style="width:10%">Choose Assisnment</th>
						<th style="width:20%">Task name</th>
						<th style="width:15%">Start time</th>
						<th style="width:10%">End time</th>
						<th style="width:10%">Min title brigate</th>
                        <th style="width:10%">Tag</th>
					</tr>
					<!-- Use this as template to import Employees -->
					{% for emp in data  %}
					<tr>
						<td>
							<input type="radio" checked="checked" name="check" value="{{ emp.taskName }}/{{ emp.tag }}">
						</td>
						<td>{{ emp.taskName }}</td>
						<td>{{ emp.start_fix }}</td>
						<td>{{ emp.end_fix }}</td>
						<td>{{ emp.min_title_fix }}</td>
                        <td>{{ emp.tag }}</td>
					</tr>
                {% endfor %}
				</tbody>
			</table>

			<ul>
				 <input type="submit" name="submit" value="Edit Assignment">
                <input type="hidden" name="id" value="{{ id }}">
                <input type="submit" name="submit" value="Create Assignment">
                <input type="submit" name="submit" value="Delete Assignment">
			</ul>
             </form>
		</div>
	</main>
</body>

</html>

schedule/templates/schedule/editassign.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Assignment Editor</title>
	<meta name="description" content="Edit Employee Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->


	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="back" method="post" action="{% url 'user:setup' %}">
                {% csrf_token %}
              <input type="submit" name="empl" value="Back">
              <input type="hidden" name="id" value={{ id }} >

        </form>
	</nav>
</header>
<body>
	<main>
        <form method="post" action="{% url 'schedule:edit_create_assi' %}">
            {% csrf_token %}
		<div class="large">

			<div class="editemploy">
				<div class="editemployrow">
					<h2>Task name:</h2>
					<input type="text"  name="taskname" value="{{ data.taskName }}">
				</div>
				<div class="editemployrow">
					<h2>Start time :</h2>
					<input type="text"  name="start" value="{{ data.start_fix }}">
				</div>
                <div class="editemployrow">
					<h2>End time :</h2>
					<input type="text"  name="end" value="{{ data.end_fix}}">
				</div>
				<div class="editemployrow">
					<h2>Min Title Brigade:</h2>
					<select name="title" id="brtitle">
						<option value="4">Kitchen Leader</option>
						<option value="3">Sous Chef</option>
						<option value="2">Line Cook</option>
						<option value="1">Junior Cook</option>
						<option value="0">Dishwasher</option>
					</select>
				</div>
				<div class="editemployrow">
					<h2>Tag:</h2>
					<select name="tag" id="brtitle">
						<option value="AM">AM</option>
						<option value="PM">PM</option>
                    </select>
				</div>

			</div>
			<ul>
                <input type="hidden" name="id" value="{{ id }}">
                <input type="hidden" name="old" value="{{ data.taskName }}/{{ data.tag }}">
                <input type="submit" value="Accept Edit" name="submit">
			</ul>
		</div>
        </form>
	</main>
</body>

</html>

schedule/templates/schedule/editemploy.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Employee Editor</title>
	<meta name="description" content="Edit Employee Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->


	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="back" method="post" action="{% url 'user:setup' %}">
                {% csrf_token %}
              <input type="submit" name="empl" value="Back">
              <input type="hidden" name="id" value={{ id }} >

        </form>
	</nav>
</header>
<body>
	<main>
    <form method="post" action="{% url 'schedule:edit_create' %}">
    {% csrf_token %}
		<div class="large">

			<div class="editemploy">
				<div class="editemployrow">
					<h2>Employee ID:</h2>
					<input type="text" value="{{ data.eid }}" name="eid">
				</div>
				<div class="editemployrow">
					<h2>Name:</h2>
					<input type="text" value="{{ data.name}}" name="name">
				</div>
				<div class="editemployrow">

					<h2>Brigade Title:</h2>
					<select name="title" id="brtitle">
						<option value="5">Kitchen Leader</option>
						<option value="4">Sous Chef</option>
						<option value="3">Line Cook</option>
						<option value="2">Junior Cook</option>
						<option value="1">Dishwasher</option>
					</select>
				</div>
				<div class="editemployrow">
					<h2>Time Off<br/>Reason - Unavailable Hours:</h2>
					<p id="timeoff" >
                        {% for untime in data.UnavailableTime %}
                            {{ untime.reason }}-{{ untime.day }}-{{ untime.startfix }}-{{ untime.endfix }}
							<br>
                        {% endfor %}
					</p>
				</div>
				<div class="editemployrow">
					<h2>Min Hours:</h2>
					<input type="text" value="{{ data.minhour }}" name="minhour" min="0" max="84" step="1">
				</div>
				<div class="editemployrow">
					<h2>Max Hours:</h2>
					<input type="text" value="{{ data.maxhour }}" name="maxhour" min="0" max="84" step="1">
				</div>

			</div>
			<ul>
                <input type="hidden" name="id" value="{{ id }}">
                <input type="hidden" name="old" value="{{ data.eid }}">
                <input type="submit" value="Accept Edit" name="submit">
                <input type="submit" value="Navigate Unavailable Time" name="submit">
			</ul>

		</div>
    </form>
	</main>
</body>

</html>

schedule/templates/schedule/editshift.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Employee Editor</title>
	<meta name="description" content="Edit Employee Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->


	<link rel="stylesheet" href="{% static 'main.css' %}">
	<script src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>
	<nav id="nav_main">
        <form id="back" method="post" action="{% url 'user:setup' %}">
                {% csrf_token %}
              <input type="submit" name="empl" value="Back">
              <input type="hidden" name="id" value={{ id }} >

        </form>
	</nav>
</header>
<body>
	<main>
        <form method="post" action="{% url 'schedule:edit_create_shift' %}">
            {% csrf_token %}
		<div class="large">
            <h2> Day of week: {{ day }}</h2>
            <h2> Tag: {{ tag }}</h2>
            <br>
            {% for i in list %}
					<p>{{ i.l }}:</p>
					<input type="number"  name="{{ i.l }}" value="{{ i.n }}" min="0">
			{% endfor %}

			<ul>
                <input type="hidden" name="id" value="{{ id }}">
                <input type="hidden" name="old" value="{{ day }}/{{ tag }}">
                <input type="submit" value="Accept Edit" name="submit">
			</ul>
		</div>
        </form>
	</main>
</body>

</html>

schedule/templates/schedule/employee.html
<!doctype html>
<html class="no-js" lang="">

<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Employees</title>
	<meta name="description" content="Current Employees Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifepythonst" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css' %}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<header>

	<nav id="nav_main">
        <form id="sett" method="post" action="{% url 'user:setting' %}" class="right">
            {% csrf_token %}
              <input type="submit" name="setting" value="Back" class="right">
              <input type="hidden" name="id" value={{ id }} >
        </form>
	</nav>
</header>
<body>
	<main>
		<div class="large">
            <form action="{% url 'schedule:editempl' %}" method="post">
            {% csrf_token %}
			<table>
				<tbody class="emp-list">
					<tr class="header">
						<th style="width:10%">Choose Employee</th>
                        <th style="width:10%">EID</th>
						<th style="width:20%">Name</th>
						<th style="width:15%">Brigade Title</th>
						<th>Time Off<br/>Reason - Unavailable Hours</th>
						<th style="width:10%">Min Hours</th>
						<th style="width:10%">Max Hours</th>
					</tr>
					<!-- Use this as template to import Employees -->
					{% for emp in data  %}
					<tr>
						<td>
							<input type="radio" checked="checked" name="check" value="{{ emp.eid }}">
						</td>
                        <td>{{ emp.eid }}</td>
						<td>{{ emp.name }}</td>
						<td>{{ emp.ti }}</td>

						<td>
                        {% for untime in emp.UnavailableTime %}
                        {{ untime.reason }}-{{ untime.day }}-{{ untime.startfix }}-{{ untime.endfix }}
							<br>
                        {% endfor %}
						</td>
						<td>{{ emp.minhour }}</td>
						<td>{{ emp.maxhour }}</td>
					</tr>
                {% endfor %}
				</tbody>
			</table>

			<ul>
				 <input type="submit" name="submit" value="Edit Employee">
                <input type="hidden" name="id" value="{{ id }}">
                <input type="submit" name="submit" value="Create Employee">
                <input type="submit" name="submit" value="Delete Employee">
			</ul>
             </form>
		</div>
	</main>
</body>

</html>

schedule/templates/schedule/res.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
	<title>FGS - Register</title>
	<meta name="description" content="Registration Page">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="manifest" href="site.webmanifest">
	<link rel="apple-touch-icon" href="icon.png">
	<!-- Place favicon.ico in the root directory -->

	<link rel="stylesheet" href="{% static 'main.css'%}">

	<script type="text/javascript" src="{% static 'main.js' %}"></script>

	<meta name="theme-color" content="#fafafa">
</head>
<body>
    <h1> The schedule create success! </h1>
    <form action="{% url 'schedule:index' %}" method="post">
                    {% csrf_token %}
        <input type="hidden" name="id" value={{ id }} >
        <input type="submit" id="save" value="Back">
    </form>

</body>
</html>